/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;

/**
 *
 * @author Family
 */
public class AssessmentPage extends javax.swing.JFrame {

    /**
     * Creates new form AssessmentPage
     */
    public AssessmentPage() {
        initComponents();
        
        groupButton1();
        groupButton2();
        groupButton3();
        groupButton4();
        groupButton5();
        groupButton6();
        groupButton7();
        groupButton8();
        groupButton9();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssessmentLB = new javax.swing.JLabel();
        UseMWBTrafficLightLB = new javax.swing.JLabel();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        TrackersFilledLB = new javax.swing.JLabel();
        UseOfSCLB = new javax.swing.JLabel();
        PeerAssessmentLB = new javax.swing.JLabel();
        TeacherAssessmentLB = new javax.swing.JLabel();
        SubjectSpecificDocumentLB = new javax.swing.JLabel();
        PastPapersLB = new javax.swing.JLabel();
        FeedbackResponseLB = new javax.swing.JLabel();
        TeacherAssessmentFoldersLB = new javax.swing.JLabel();
        ACommentsLB = new javax.swing.JLabel();
        ACommentsField = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        UseMWBTrafficLightY = new javax.swing.JRadioButton();
        UseMWBTrafficLightN = new javax.swing.JRadioButton();
        TrackersFilledY = new javax.swing.JRadioButton();
        TrackersFilledN = new javax.swing.JRadioButton();
        UseOfSCY = new javax.swing.JRadioButton();
        UseOfSCN = new javax.swing.JRadioButton();
        PeerAssessmentY = new javax.swing.JRadioButton();
        PeerAssessmentN = new javax.swing.JRadioButton();
        TeacherAssessmentY = new javax.swing.JRadioButton();
        TeacherAssessmentN = new javax.swing.JRadioButton();
        SubjectSpecificDocumentY = new javax.swing.JRadioButton();
        SubjectSpecificDocumentN = new javax.swing.JRadioButton();
        PastPapersY = new javax.swing.JRadioButton();
        PastPapersN = new javax.swing.JRadioButton();
        TeacherAssessmentFoldersY = new javax.swing.JRadioButton();
        TeacherAssessmentFoldersN = new javax.swing.JRadioButton();
        FeedbackResponseY = new javax.swing.JRadioButton();
        FeedbackResponseN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(480, 80));
        setResizable(false);

        AssessmentLB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AssessmentLB.setText("Fill in the Data for Assessment");

        UseMWBTrafficLightLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UseMWBTrafficLightLB.setText("Students respond promptly to the use of MWBs/Traffic Light Cards");

        YesLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoLB.setText("No");

        TrackersFilledLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TrackersFilledLB.setText("Trackers are filled in and up to date");

        UseOfSCLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UseOfSCLB.setText("There is evidence of the use of grade/success criteria in assessment");

        PeerAssessmentLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PeerAssessmentLB.setText("There is evidence of self/peer assessment");

        TeacherAssessmentLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TeacherAssessmentLB.setText("There is evidence of teacher assessment");

        SubjectSpecificDocumentLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubjectSpecificDocumentLB.setText("There is evidence of use of students using a subject specification document");

        PastPapersLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PastPapersLB.setText("There is evidence of use of Past Paper Questions/Grade Criteria/Mark Schemes");

        FeedbackResponseLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FeedbackResponseLB.setText("There is evidence of students responding to teacher feedback");

        TeacherAssessmentFoldersLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TeacherAssessmentFoldersLB.setText("There is evidence of teacher assessment in folders (where folders seen)");

        ACommentsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ACommentsLB.setText("Additional Comments");

        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        UseMWBTrafficLightN.setSelected(true);

        TrackersFilledN.setSelected(true);

        UseOfSCN.setSelected(true);

        PeerAssessmentN.setSelected(true);

        TeacherAssessmentN.setSelected(true);

        SubjectSpecificDocumentN.setSelected(true);

        PastPapersN.setSelected(true);

        TeacherAssessmentFoldersN.setSelected(true);

        FeedbackResponseN.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(AssessmentLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoLB)
                    .addComponent(UseMWBTrafficLightN)
                    .addComponent(TrackersFilledN)
                    .addComponent(UseOfSCN)
                    .addComponent(PeerAssessmentN)
                    .addComponent(TeacherAssessmentN)
                    .addComponent(SubjectSpecificDocumentN)
                    .addComponent(PastPapersN)
                    .addComponent(TeacherAssessmentFoldersN)
                    .addComponent(FeedbackResponseN))
                .addGap(252, 252, 252))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PastPapersLB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TrackersFilledLB)
                                .addComponent(UseMWBTrafficLightLB)
                                .addComponent(UseOfSCLB)
                                .addComponent(PeerAssessmentLB)
                                .addComponent(TeacherAssessmentLB)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(SubjectSpecificDocumentLB)))
                    .addComponent(TeacherAssessmentFoldersLB)
                    .addComponent(FeedbackResponseLB)
                    .addComponent(ACommentsLB)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YesLB)
                    .addComponent(ACommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UseMWBTrafficLightY)
                    .addComponent(TrackersFilledY)
                    .addComponent(UseOfSCY)
                    .addComponent(PeerAssessmentY)
                    .addComponent(TeacherAssessmentY)
                    .addComponent(SubjectSpecificDocumentY)
                    .addComponent(PastPapersY)
                    .addComponent(TeacherAssessmentFoldersY)
                    .addComponent(FeedbackResponseY))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(AssessmentLB)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(YesLB)
                                            .addComponent(NoLB))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(UseMWBTrafficLightLB))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                                .addComponent(UseMWBTrafficLightY))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UseMWBTrafficLightN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TrackersFilledLB)
                                    .addComponent(TrackersFilledY)
                                    .addComponent(TrackersFilledN))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UseOfSCLB)
                                    .addComponent(UseOfSCY)
                                    .addComponent(UseOfSCN))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PeerAssessmentN)
                                    .addComponent(PeerAssessmentLB)
                                    .addComponent(PeerAssessmentY))
                                .addGap(18, 18, 18)
                                .addComponent(TeacherAssessmentLB))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeacherAssessmentY, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TeacherAssessmentN, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubjectSpecificDocumentLB)
                            .addComponent(SubjectSpecificDocumentN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubjectSpecificDocumentY)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PastPapersN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TeacherAssessmentFoldersN))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PastPapersLB)
                                .addComponent(PastPapersY))
                            .addGap(18, 18, 18)
                            .addComponent(TeacherAssessmentFoldersLB))
                        .addComponent(TeacherAssessmentFoldersY)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FeedbackResponseLB)
                    .addComponent(FeedbackResponseY)
                    .addComponent(FeedbackResponseN))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACommentsLB)
                    .addComponent(ACommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton1() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(UseMWBTrafficLightY);
        bg1.add(UseMWBTrafficLightN);
    }
    
    private void groupButton2() {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(TrackersFilledY);
        bg2.add(TrackersFilledN);
    }
    
    private void groupButton3() {
        ButtonGroup bg3 = new ButtonGroup();
        
        bg3.add(UseOfSCY);
        bg3.add(UseOfSCN);
    }
    
    private void groupButton4() {
        ButtonGroup bg4 = new ButtonGroup();
        
        bg4.add(PeerAssessmentY);
        bg4.add(PeerAssessmentN);
    }
    
    private void groupButton5() {
        ButtonGroup bg5 = new ButtonGroup();
        
        bg5.add(TeacherAssessmentY);
        bg5.add(TeacherAssessmentN);
    }
    
    private void groupButton6() {
        ButtonGroup bg6 = new ButtonGroup();
        
        bg6.add(SubjectSpecificDocumentY);
        bg6.add(SubjectSpecificDocumentN);
    }
    
    private void groupButton7() {
        ButtonGroup bg7 = new ButtonGroup();
        
        bg7.add(PastPapersY);
        bg7.add(PastPapersN);
    }
    
    private void groupButton8() {
        ButtonGroup bg8 = new ButtonGroup();
        
        bg8.add(TeacherAssessmentFoldersY);
        bg8.add(TeacherAssessmentFoldersN);
    }
    
    private void groupButton9() {
        ButtonGroup bg9 = new ButtonGroup();
        
        bg9.add(FeedbackResponseY);
        bg9.add(FeedbackResponseN);
    }
    
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        
        boolean UseMWBTrafficLight = UseMWBTrafficLightY.isSelected();
        boolean TrackersFilled = TrackersFilledY.isSelected();
        boolean UseOfSC = UseOfSCY.isSelected();
        boolean PeerAssessment = PeerAssessmentY.isSelected();
        boolean TeacherAssessment = TeacherAssessmentY.isSelected();
        boolean SubjectSpecificDocument = SubjectSpecificDocumentY.isSelected();
        boolean PastPapers = PastPapersY.isSelected();
        boolean TeacherAssessmentFolders = TeacherAssessmentFoldersY.isSelected();
        boolean FeedbackResponse = FeedbackResponseY.isSelected();
        String AComments = ACommentsField.getText();
        
        DataTempStorage.AssessmentStore(UseMWBTrafficLight, TrackersFilled, UseOfSC, PeerAssessment, TeacherAssessment, SubjectSpecificDocument, PastPapers, TeacherAssessmentFolders, FeedbackResponse, AComments);
        
        new POESFEPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssessmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssessmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssessmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssessmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssessmentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACommentsField;
    private javax.swing.JLabel ACommentsLB;
    private javax.swing.JLabel AssessmentLB;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel FeedbackResponseLB;
    private javax.swing.JRadioButton FeedbackResponseN;
    private javax.swing.JRadioButton FeedbackResponseY;
    private javax.swing.JLabel NoLB;
    private javax.swing.JLabel PastPapersLB;
    private javax.swing.JRadioButton PastPapersN;
    private javax.swing.JRadioButton PastPapersY;
    private javax.swing.JLabel PeerAssessmentLB;
    private javax.swing.JRadioButton PeerAssessmentN;
    private javax.swing.JRadioButton PeerAssessmentY;
    private javax.swing.JLabel SubjectSpecificDocumentLB;
    private javax.swing.JRadioButton SubjectSpecificDocumentN;
    private javax.swing.JRadioButton SubjectSpecificDocumentY;
    private javax.swing.JLabel TeacherAssessmentFoldersLB;
    private javax.swing.JRadioButton TeacherAssessmentFoldersN;
    private javax.swing.JRadioButton TeacherAssessmentFoldersY;
    private javax.swing.JLabel TeacherAssessmentLB;
    private javax.swing.JRadioButton TeacherAssessmentN;
    private javax.swing.JRadioButton TeacherAssessmentY;
    private javax.swing.JLabel TrackersFilledLB;
    private javax.swing.JRadioButton TrackersFilledN;
    private javax.swing.JRadioButton TrackersFilledY;
    private javax.swing.JLabel UseMWBTrafficLightLB;
    private javax.swing.JRadioButton UseMWBTrafficLightN;
    private javax.swing.JRadioButton UseMWBTrafficLightY;
    private javax.swing.JLabel UseOfSCLB;
    private javax.swing.JRadioButton UseOfSCN;
    private javax.swing.JRadioButton UseOfSCY;
    private javax.swing.JLabel YesLB;
    // End of variables declaration//GEN-END:variables
}
