/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;


        
public class InputDataPage extends javax.swing.JFrame {

    /**
     * Creates new form ClassDetailsPage
     */
    public InputDataPage() {
        initComponents();
        
        groupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Classdetailspage = new javax.swing.JPanel();
        DateLB = new javax.swing.JLabel();
        DateEmptyLB = new javax.swing.JLabel();
        TeacherEmptyLB = new javax.swing.JLabel();
        PeriodLB = new javax.swing.JLabel();
        EnterDetails = new javax.swing.JLabel();
        YrGrpLB = new javax.swing.JLabel();
        LevelLB = new javax.swing.JLabel();
        TeacherField = new javax.swing.JTextField();
        SubLB = new javax.swing.JLabel();
        GrpCombo = new javax.swing.JComboBox<>();
        LvlCombo = new javax.swing.JComboBox<>();
        YrGrpCombo = new javax.swing.JComboBox<>();
        DateField = new javax.swing.JTextField();
        SubCombo = new javax.swing.JComboBox<>();
        DayLB = new javax.swing.JLabel();
        DayCombo = new javax.swing.JComboBox<>();
        PeriodCombo = new javax.swing.JComboBox<>();
        TeacherLB = new javax.swing.JLabel();
        ContinueButtonCD = new javax.swing.JButton();
        GrpLB = new javax.swing.JLabel();
        SetLB = new javax.swing.JLabel();
        SetCombo = new javax.swing.JComboBox<>();
        LBScrollPane = new javax.swing.JScrollPane();
        LearningBehaviourPage = new javax.swing.JPanel();
        TitleLB = new javax.swing.JLabel();
        StudentListeningY = new javax.swing.JRadioButton();
        StudentPostureLB = new javax.swing.JLabel();
        StudentListeningN = new javax.swing.JRadioButton();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        StudentRespectY = new javax.swing.JRadioButton();
        StudentRespectN = new javax.swing.JRadioButton();
        StudentSilenceLB = new javax.swing.JLabel();
        StudentCoatHatOffY = new javax.swing.JRadioButton();
        StudentEngagedLB = new javax.swing.JLabel();
        StudentCoatHatOffN = new javax.swing.JRadioButton();
        StudentFocusLB = new javax.swing.JLabel();
        NoPhoneY = new javax.swing.JRadioButton();
        StudentListeningLB = new javax.swing.JLabel();
        NoPhoneN = new javax.swing.JRadioButton();
        StudentRespectLB = new javax.swing.JLabel();
        StudentCoatHatOffLB = new javax.swing.JLabel();
        NoPhoneLB = new javax.swing.JLabel();
        LBCommentField = new javax.swing.JTextField();
        LBCommentsLB = new javax.swing.JLabel();
        ContinueButtonLB = new javax.swing.JButton();
        StudentPostureY = new javax.swing.JRadioButton();
        StudentPostureN = new javax.swing.JRadioButton();
        StudentSilenceY = new javax.swing.JRadioButton();
        StudentSilenceN = new javax.swing.JRadioButton();
        StudentEngagedY = new javax.swing.JRadioButton();
        StudentEngagedN = new javax.swing.JRadioButton();
        StudentFocusY = new javax.swing.JRadioButton();
        StudentFocusN = new javax.swing.JRadioButton();
        POPScrollPane = new javax.swing.JScrollPane();
        POPPage = new javax.swing.JPanel();
        SignedY = new javax.swing.JRadioButton();
        SignedLB = new javax.swing.JLabel();
        SignedN = new javax.swing.JRadioButton();
        PrepDateLB = new javax.swing.JLabel();
        PrepDateY = new javax.swing.JRadioButton();
        NoGapsLB = new javax.swing.JLabel();
        PrepDateN = new javax.swing.JRadioButton();
        POPCommentsLB = new javax.swing.JLabel();
        NoGapsY = new javax.swing.JRadioButton();
        POPCommentsField = new javax.swing.JTextField();
        NoGapsN = new javax.swing.JRadioButton();
        ContinueButtonPOP = new javax.swing.JButton();
        POPTitle = new javax.swing.JLabel();
        NeatY = new javax.swing.JRadioButton();
        NeatLB = new javax.swing.JLabel();
        NeatN = new javax.swing.JRadioButton();
        YesLB1 = new javax.swing.JLabel();
        WOWReadingBookFilledY = new javax.swing.JRadioButton();
        NoLB1 = new javax.swing.JLabel();
        WOWReadingBookFilledN = new javax.swing.JRadioButton();
        WOWReadingBookFilledLB = new javax.swing.JLabel();
        POBFEScrollPane = new javax.swing.JScrollPane();
        POBFEPage = new javax.swing.JPanel();
        CorrectPenY = new javax.swing.JRadioButton();
        POBFECommentsField = new javax.swing.JTextField();
        CorrectPenN = new javax.swing.JRadioButton();
        ContinueButtonPOBFE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CoveredY = new javax.swing.JRadioButton();
        CoveredLB = new javax.swing.JLabel();
        CoveredN = new javax.swing.JRadioButton();
        YesLB2 = new javax.swing.JLabel();
        HandwritingNeatY = new javax.swing.JRadioButton();
        NoLB2 = new javax.swing.JLabel();
        HandwritingNeatN = new javax.swing.JRadioButton();
        HandwritingNeatLB = new javax.swing.JLabel();
        UnderlinedY = new javax.swing.JRadioButton();
        UnderlinedLB = new javax.swing.JLabel();
        UnderlinedN = new javax.swing.JRadioButton();
        SheetsNeatLB = new javax.swing.JLabel();
        SheetsNeatY = new javax.swing.JRadioButton();
        CorrectPenLB = new javax.swing.JLabel();
        SheetsNeatN = new javax.swing.JRadioButton();
        POBFECommentsLB = new javax.swing.JLabel();
        CorrectPen2LB = new javax.swing.JLabel();
        AScrollPane = new javax.swing.JScrollPane();
        AssessmentPage = new javax.swing.JPanel();
        FeedbackResponseN = new javax.swing.JRadioButton();
        ACommentsLB = new javax.swing.JLabel();
        ACommentsField = new javax.swing.JTextField();
        ContinueButtonA = new javax.swing.JButton();
        UseMWBTrafficLightY = new javax.swing.JRadioButton();
        UseMWBTrafficLightN = new javax.swing.JRadioButton();
        TrackersFilledY = new javax.swing.JRadioButton();
        TrackersFilledN = new javax.swing.JRadioButton();
        UseOfSCY = new javax.swing.JRadioButton();
        UseOfSCN = new javax.swing.JRadioButton();
        PeerAssessmentY = new javax.swing.JRadioButton();
        AssessmentLB = new javax.swing.JLabel();
        UseMWBTrafficLightLB = new javax.swing.JLabel();
        PeerAssessmentN = new javax.swing.JRadioButton();
        TeacherAssessmentY = new javax.swing.JRadioButton();
        YesLB3 = new javax.swing.JLabel();
        TeacherAssessmentN = new javax.swing.JRadioButton();
        NoLB3 = new javax.swing.JLabel();
        SubjectSpecificDocumentY = new javax.swing.JRadioButton();
        TrackersFilledLB = new javax.swing.JLabel();
        SubjectSpecificDocumentN = new javax.swing.JRadioButton();
        UseOfSCLB = new javax.swing.JLabel();
        PastPapersY = new javax.swing.JRadioButton();
        PeerAssessmentLB = new javax.swing.JLabel();
        PastPapersN = new javax.swing.JRadioButton();
        TeacherAssessmentLB = new javax.swing.JLabel();
        TeacherAssessmentFoldersY = new javax.swing.JRadioButton();
        SubjectSpecificDocumentLB = new javax.swing.JLabel();
        TeacherAssessmentFoldersN = new javax.swing.JRadioButton();
        PastPapersLB = new javax.swing.JLabel();
        FeedbackResponseY = new javax.swing.JRadioButton();
        FeedbackResponseLB = new javax.swing.JLabel();
        TeacherAssessmentFoldersLB = new javax.swing.JLabel();
        POESFEScrollPane = new javax.swing.JScrollPane();
        POESFEPage = new javax.swing.JPanel();
        ESSystemY = new javax.swing.JRadioButton();
        NotesSystemLB = new javax.swing.JLabel();
        ESSystemN = new javax.swing.JRadioButton();
        FolderNeatLB = new javax.swing.JLabel();
        ESSystemLB = new javax.swing.JLabel();
        POESFECommentsLB = new javax.swing.JLabel();
        POESFECommentsField = new javax.swing.JTextField();
        ContinueButtonPOESFE = new javax.swing.JButton();
        NotesSystemY = new javax.swing.JRadioButton();
        POESFELB = new javax.swing.JLabel();
        NotesSystemN = new javax.swing.JRadioButton();
        POESFELB2 = new javax.swing.JLabel();
        FolderNeatY = new javax.swing.JRadioButton();
        YesLB4 = new javax.swing.JLabel();
        FolderNeatN = new javax.swing.JRadioButton();
        NoLB4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(550, 20));
        setPreferredSize(new java.awt.Dimension(866, 1000));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        Classdetailspage.setName(""); // NOI18N
        Classdetailspage.setPreferredSize(new java.awt.Dimension(864, 844));
        Classdetailspage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        DateLB.setText("Date");
        Classdetailspage.add(DateLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 359, -1, -1));

        DateEmptyLB.setForeground(new java.awt.Color(255, 0, 0));
        DateEmptyLB.setText("Field is Empty");
        Classdetailspage.add(DateEmptyLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 367, -1, -1));

        TeacherEmptyLB.setForeground(new java.awt.Color(255, 0, 0));
        TeacherEmptyLB.setText("Field is Empty");
        Classdetailspage.add(TeacherEmptyLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        PeriodLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PeriodLB.setText("Period");
        Classdetailspage.add(PeriodLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 448, -1, -1));

        EnterDetails.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        EnterDetails.setText("Enter the Details of the Class");
        Classdetailspage.add(EnterDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 25, -1, -1));

        YrGrpLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YrGrpLB.setText("Year Group");
        Classdetailspage.add(YrGrpLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 183, -1, -1));

        LevelLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LevelLB.setText("Level");
        Classdetailspage.add(LevelLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 271, -1, -1));

        TeacherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherFieldActionPerformed(evt);
            }
        });
        TeacherField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TeacherFieldKeyReleased(evt);
            }
        });
        Classdetailspage.add(TeacherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 495, 158, 25));

        SubLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SubLB.setText("Subject");
        Classdetailspage.add(SubLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 315, -1, -1));

        GrpCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trainee", "Newly Qualified" }));
        Classdetailspage.add(GrpCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 543, 158, -1));

        LvlCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nurture", "Core", "Higher", "Advanced" }));
        Classdetailspage.add(LvlCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 275, 158, 22));

        YrGrpCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13" }));
        Classdetailspage.add(YrGrpCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 187, 158, 22));

        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        DateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DateFieldKeyReleased(evt);
            }
        });
        Classdetailspage.add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 362, 158, 24));

        SubCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "English Elective", "Maths", "Science", "French", "German", "Spanish", "Latin", "History", "Geography", "R.E.", "Ethics", "P.E.", "Computer Science (KS4)", "ICT (KS4)", "Computing (KS3)", "Art", "Music", "Drama", "Food Technology", "Study", "Life Skills" }));
        Classdetailspage.add(SubCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 319, 158, 22));

        DayLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        DayLB.setText("Day");
        Classdetailspage.add(DayLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 404, -1, -1));

        DayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        Classdetailspage.add(DayCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 408, 158, 22));

        PeriodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        Classdetailspage.add(PeriodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 452, 158, 22));

        TeacherLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TeacherLB.setText("Duty Teacher");
        Classdetailspage.add(TeacherLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 492, -1, -1));

        ContinueButtonCD.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ContinueButtonCD.setText("Continue");
        ContinueButtonCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonCDActionPerformed(evt);
            }
        });
        Classdetailspage.add(ContinueButtonCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, 245, 104));

        GrpLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        GrpLB.setText("Teacher Group");
        Classdetailspage.add(GrpLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 538, -1, -1));

        SetLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SetLB.setText("Set");
        Classdetailspage.add(SetLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 227, 88, -1));

        SetCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        Classdetailspage.add(SetCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 231, 158, 22));

        getContentPane().add(Classdetailspage, "card2");

        LBScrollPane.setHorizontalScrollBar(null);
        LBScrollPane.setPreferredSize(new java.awt.Dimension(866, 844));

        LearningBehaviourPage.setPreferredSize(new java.awt.Dimension(866, 844));

        TitleLB.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        TitleLB.setText("Fill in the Data for Learning Behaviour");

        StudentListeningY.setSelected(true);

        StudentPostureLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentPostureLB.setText("Student's Posture shows that they are alert and ready to learn");

        YesLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoLB.setText("No");

        StudentRespectY.setSelected(true);

        StudentSilenceLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentSilenceLB.setText("Students remain silent unless invited to speak");

        StudentCoatHatOffY.setSelected(true);

        StudentEngagedLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentEngagedLB.setText("Students appear engaged");

        StudentFocusLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentFocusLB.setText("Students remain on task during independent work");

        NoPhoneY.setSelected(true);

        StudentListeningLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentListeningLB.setText("Students display good listening behaviour");

        StudentRespectLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentRespectLB.setText("Students act respectfully towards the teacher and each other");

        StudentCoatHatOffLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentCoatHatOffLB.setText("Coats and Hats have been taken off");

        NoPhoneLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoPhoneLB.setText("No phones out (unless directed by the teacher)");

        LBCommentsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LBCommentsLB.setText("Additional Comments");

        ContinueButtonLB.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ContinueButtonLB.setText("Continue");
        ContinueButtonLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonLBActionPerformed(evt);
            }
        });

        StudentPostureY.setSelected(true);

        StudentSilenceY.setSelected(true);

        StudentEngagedY.setSelected(true);

        StudentFocusY.setSelected(true);

        javax.swing.GroupLayout LearningBehaviourPageLayout = new javax.swing.GroupLayout(LearningBehaviourPage);
        LearningBehaviourPage.setLayout(LearningBehaviourPageLayout);
        LearningBehaviourPageLayout.setHorizontalGroup(
            LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LearningBehaviourPageLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LearningBehaviourPageLayout.createSequentialGroup()
                        .addComponent(LBCommentsLB)
                        .addGap(51, 51, 51)
                        .addComponent(LBCommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LearningBehaviourPageLayout.createSequentialGroup()
                        .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StudentCoatHatOffLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NoPhoneLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentRespectLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentListeningLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentFocusLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentEngagedLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentSilenceLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentPostureLB, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(87, 87, 87)
                                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentCoatHatOffY)
                                    .addComponent(NoPhoneY)
                                    .addComponent(StudentRespectY)
                                    .addComponent(StudentListeningY)
                                    .addComponent(StudentFocusY)
                                    .addComponent(StudentEngagedY)
                                    .addComponent(StudentSilenceY)
                                    .addComponent(StudentPostureY)
                                    .addComponent(YesLB))
                                .addGap(53, 53, 53)
                                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NoPhoneN)
                                        .addComponent(StudentFocusN)
                                        .addComponent(StudentEngagedN)
                                        .addComponent(StudentSilenceN)
                                        .addComponent(StudentPostureN))
                                    .addComponent(NoLB)))
                            .addComponent(StudentRespectN)
                            .addComponent(StudentCoatHatOffN)
                            .addComponent(StudentListeningN))
                        .addGap(109, 109, 109))))
            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(ContinueButtonLB, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(TitleLB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LearningBehaviourPageLayout.setVerticalGroup(
            LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(TitleLB)
                        .addGap(54, 54, 54)
                        .addComponent(YesLB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LearningBehaviourPageLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(NoLB)))
                .addGap(18, 18, 18)
                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentPostureN)
                    .addComponent(StudentPostureY)
                    .addComponent(StudentPostureLB))
                .addGap(18, 18, 18)
                .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                        .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentSilenceN)
                            .addComponent(StudentSilenceY))
                        .addGap(18, 18, 18)
                        .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                                .addComponent(StudentEngagedN)
                                .addGap(24, 24, 24)
                                .addComponent(StudentFocusN)
                                .addGap(18, 18, 18)
                                .addComponent(StudentListeningN)
                                .addGap(18, 18, 18)
                                .addComponent(StudentRespectN)
                                .addGap(18, 18, 18)
                                .addComponent(StudentCoatHatOffN)
                                .addGap(18, 18, 18)
                                .addComponent(NoPhoneN))
                            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                                .addComponent(StudentEngagedY)
                                .addGap(24, 24, 24)
                                .addComponent(StudentFocusY)
                                .addGap(18, 18, 18)
                                .addComponent(StudentListeningY)
                                .addGap(18, 18, 18)
                                .addComponent(StudentRespectY)
                                .addGap(18, 18, 18)
                                .addComponent(StudentCoatHatOffY)
                                .addGap(18, 18, 18)
                                .addComponent(NoPhoneY))
                            .addGroup(LearningBehaviourPageLayout.createSequentialGroup()
                                .addComponent(StudentEngagedLB)
                                .addGap(18, 18, 18)
                                .addComponent(StudentFocusLB)
                                .addGap(18, 18, 18)
                                .addComponent(StudentListeningLB)
                                .addGap(18, 18, 18)
                                .addComponent(StudentRespectLB)
                                .addGap(18, 18, 18)
                                .addComponent(StudentCoatHatOffLB)
                                .addGap(18, 18, 18)
                                .addComponent(NoPhoneLB)))
                        .addGap(69, 69, 69)
                        .addGroup(LearningBehaviourPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBCommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBCommentsLB))
                        .addGap(40, 40, 40)
                        .addComponent(ContinueButtonLB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StudentSilenceLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBScrollPane.setViewportView(LearningBehaviourPage);

        getContentPane().add(LBScrollPane, "card4");

        POPScrollPane.setHorizontalScrollBar(null);
        POPScrollPane.setPreferredSize(new java.awt.Dimension(866, 844));

        POPPage.setPreferredSize(new java.awt.Dimension(866, 844));

        SignedY.setSelected(true);

        SignedLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SignedLB.setText("Planners are signed weekly by parent and tutor");

        PrepDateLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PrepDateLB.setText("Prep/HWKs are recorded clearly with due date");

        PrepDateY.setSelected(true);

        NoGapsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoGapsLB.setText("No gaps are left - if 'No Prep', a reason is recorded");

        POPCommentsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        POPCommentsLB.setText("Additional Comments");

        NoGapsY.setSelected(true);

        NoGapsN.setToolTipText("");

        ContinueButtonPOP.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ContinueButtonPOP.setText("Continue");
        ContinueButtonPOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonPOPActionPerformed(evt);
            }
        });

        POPTitle.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        POPTitle.setText("Fill in the Data for Personal Organisation: Planners");

        NeatY.setSelected(true);

        NeatLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NeatLB.setText("Planners are kept neat with no scribbles/doodles etc.");

        YesLB1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YesLB1.setText("Yes");

        WOWReadingBookFilledY.setSelected(true);

        NoLB1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoLB1.setText("No");

        WOWReadingBookFilledLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        WOWReadingBookFilledLB.setText("WOW/Literacy Focus and Current Reading Book filled in");

        javax.swing.GroupLayout POPPageLayout = new javax.swing.GroupLayout(POPPage);
        POPPage.setLayout(POPPageLayout);
        POPPageLayout.setHorizontalGroup(
            POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POPPageLayout.createSequentialGroup()
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POPPageLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(POPCommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(POPPageLayout.createSequentialGroup()
                                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WOWReadingBookFilledLB)
                                    .addComponent(NeatLB)
                                    .addComponent(SignedLB)
                                    .addComponent(PrepDateLB)
                                    .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(POPCommentsLB)
                                        .addComponent(NoGapsLB)))
                                .addGap(62, 62, 62)
                                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POPPageLayout.createSequentialGroup()
                                            .addComponent(PrepDateY)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PrepDateN))
                                        .addGroup(POPPageLayout.createSequentialGroup()
                                            .addComponent(NeatY)
                                            .addGap(78, 78, 78)
                                            .addComponent(NeatN))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POPPageLayout.createSequentialGroup()
                                            .addComponent(WOWReadingBookFilledY)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(WOWReadingBookFilledN))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POPPageLayout.createSequentialGroup()
                                            .addComponent(SignedY)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SignedN))
                                        .addGroup(POPPageLayout.createSequentialGroup()
                                            .addComponent(NoGapsY)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NoGapsN)))
                                    .addGroup(POPPageLayout.createSequentialGroup()
                                        .addComponent(YesLB1)
                                        .addGap(69, 69, 69)
                                        .addComponent(NoLB1))))
                            .addComponent(POPTitle)))
                    .addGroup(POPPageLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(ContinueButtonPOP, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        POPPageLayout.setVerticalGroup(
            POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POPPageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(POPTitle)
                .addGap(62, 62, 62)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesLB1)
                    .addComponent(NoLB1))
                .addGap(29, 29, 29)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NeatLB)
                    .addComponent(NeatY)
                    .addComponent(NeatN))
                .addGap(18, 18, 18)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(WOWReadingBookFilledLB)
                        .addComponent(WOWReadingBookFilledY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(WOWReadingBookFilledN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SignedLB)
                    .addComponent(SignedN)
                    .addComponent(SignedY, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrepDateLB)
                    .addComponent(PrepDateY)
                    .addComponent(PrepDateN))
                .addGap(18, 18, 18)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NoGapsLB)
                        .addComponent(NoGapsY, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(NoGapsN))
                .addGap(65, 65, 65)
                .addGroup(POPPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POPCommentsLB)
                    .addComponent(POPCommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(ContinueButtonPOP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        POPScrollPane.setViewportView(POPPage);

        getContentPane().add(POPScrollPane, "card4");

        POBFEScrollPane.setHorizontalScrollBar(null);
        POBFEScrollPane.setPreferredSize(new java.awt.Dimension(866, 905));

        POBFEPage.setPreferredSize(new java.awt.Dimension(866, 903));

        CorrectPenY.setSelected(true);

        POBFECommentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POBFECommentsFieldActionPerformed(evt);
            }
        });

        ContinueButtonPOBFE.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ContinueButtonPOBFE.setText("Continue");
        ContinueButtonPOBFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonPOBFEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Fill in the Data for Personal Organisation: Book/Folder Etiquette");

        CoveredLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        CoveredLB.setText("Books are Covered");

        CoveredN.setSelected(true);

        YesLB2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YesLB2.setText("Yes");

        NoLB2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoLB2.setText("No");

        HandwritingNeatN.setSelected(true);

        HandwritingNeatLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        HandwritingNeatLB.setText("Students make an effort to keep handwriting neat and legible");

        UnderlinedLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        UnderlinedLB.setText("Students underline all dates and titles and record LOs");

        UnderlinedN.setSelected(true);

        SheetsNeatLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SheetsNeatLB.setText("Sheets are stuck in neatly with no loose papers");

        CorrectPenLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        CorrectPenLB.setText("Students use the correct pen");

        SheetsNeatN.setSelected(true);

        POBFECommentsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        POBFECommentsLB.setText("Additional Comments");

        CorrectPen2LB.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CorrectPen2LB.setText("(blue/black for work, red for underlining, green for assessment)");

        javax.swing.GroupLayout POBFEPageLayout = new javax.swing.GroupLayout(POBFEPage);
        POBFEPage.setLayout(POBFEPageLayout);
        POBFEPageLayout.setHorizontalGroup(
            POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POBFEPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CorrectPenN)
                    .addGroup(POBFEPageLayout.createSequentialGroup()
                        .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(YesLB2)
                            .addGroup(POBFEPageLayout.createSequentialGroup()
                                .addComponent(CoveredLB)
                                .addGap(18, 18, 18)
                                .addComponent(CoveredN))
                            .addGroup(POBFEPageLayout.createSequentialGroup()
                                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UnderlinedLB)
                                    .addComponent(HandwritingNeatLB)
                                    .addComponent(SheetsNeatLB)
                                    .addComponent(CorrectPenLB)
                                    .addComponent(CorrectPen2LB))
                                .addGap(18, 18, 18)
                                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HandwritingNeatN)
                                    .addComponent(UnderlinedN)
                                    .addComponent(SheetsNeatN)
                                    .addComponent(CorrectPenY))))
                        .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(POBFEPageLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(NoLB2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POBFEPageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CoveredY, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HandwritingNeatY, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UnderlinedY, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SheetsNeatY, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(514, 514, 514))
            .addGroup(POBFEPageLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(ContinueButtonPOBFE, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(POBFEPageLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(POBFEPageLayout.createSequentialGroup()
                        .addComponent(POBFECommentsLB)
                        .addGap(50, 50, 50)
                        .addComponent(POBFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        POBFEPageLayout.setVerticalGroup(
            POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POBFEPageLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesLB2)
                    .addComponent(NoLB2))
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POBFEPageLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CoveredLB)
                            .addComponent(CoveredN)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POBFEPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CoveredY)))
                .addGap(18, 18, 18)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HandwritingNeatLB)
                        .addComponent(HandwritingNeatY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(HandwritingNeatN))
                .addGap(18, 18, 18)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(POBFEPageLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnderlinedN)
                            .addComponent(UnderlinedY))
                        .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(POBFEPageLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SheetsNeatY))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POBFEPageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SheetsNeatN))))
                    .addGroup(POBFEPageLayout.createSequentialGroup()
                        .addComponent(UnderlinedLB)
                        .addGap(18, 18, 18)
                        .addComponent(SheetsNeatLB)))
                .addGap(18, 18, 18)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorrectPenLB)
                    .addComponent(CorrectPenY)
                    .addComponent(CorrectPenN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectPen2LB)
                .addGap(84, 84, 84)
                .addGroup(POBFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POBFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(POBFECommentsLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(ContinueButtonPOBFE, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        POBFEScrollPane.setViewportView(POBFEPage);

        getContentPane().add(POBFEScrollPane, "card5");

        AScrollPane.setHorizontalScrollBar(null);
        AScrollPane.setPreferredSize(new java.awt.Dimension(866, 1005));

        AssessmentPage.setPreferredSize(new java.awt.Dimension(866, 1003));

        ACommentsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ACommentsLB.setText("Additional Comments");

        ContinueButtonA.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ContinueButtonA.setText("Continue");
        ContinueButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonAActionPerformed(evt);
            }
        });

        UseMWBTrafficLightY.setSelected(true);

        TrackersFilledY.setSelected(true);

        UseOfSCY.setSelected(true);

        PeerAssessmentY.setSelected(true);

        AssessmentLB.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        AssessmentLB.setText("Fill in the Data for Assessment");

        UseMWBTrafficLightLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        UseMWBTrafficLightLB.setText("Students respond promptly to the use of MWBs/Traffic Light Cards");

        TeacherAssessmentY.setSelected(true);

        YesLB3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YesLB3.setText("Yes");

        NoLB3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoLB3.setText("No");

        SubjectSpecificDocumentY.setSelected(true);

        TrackersFilledLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TrackersFilledLB.setText("Trackers are filled in and up to date");

        UseOfSCLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        UseOfSCLB.setText("There is evidence of the use of grade/success criteria in assessment");

        PastPapersY.setSelected(true);

        PeerAssessmentLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PeerAssessmentLB.setText("There is evidence of self/peer assessment");

        TeacherAssessmentLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TeacherAssessmentLB.setText("There is evidence of teacher assessment");

        TeacherAssessmentFoldersY.setSelected(true);

        SubjectSpecificDocumentLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SubjectSpecificDocumentLB.setText("There is evidence of use of students using a subject specification document");

        PastPapersLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PastPapersLB.setText("There is evidence of use of Past Paper Questions/Grade Criteria/Mark Schemes");

        FeedbackResponseY.setSelected(true);

        FeedbackResponseLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        FeedbackResponseLB.setText("There is evidence of students responding to teacher feedback");

        TeacherAssessmentFoldersLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TeacherAssessmentFoldersLB.setText("There is evidence of teacher assessment in folders (where folders seen)");

        javax.swing.GroupLayout AssessmentPageLayout = new javax.swing.GroupLayout(AssessmentPage);
        AssessmentPage.setLayout(AssessmentPageLayout);
        AssessmentPageLayout.setHorizontalGroup(
            AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentPageLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(ContinueButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssessmentPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssessmentPageLayout.createSequentialGroup()
                        .addComponent(ACommentsLB)
                        .addGap(60, 60, 60)
                        .addComponent(ACommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssessmentPageLayout.createSequentialGroup()
                        .addComponent(AssessmentLB)
                        .addGap(177, 177, 177))))
            .addGroup(AssessmentPageLayout.createSequentialGroup()
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PastPapersLB)
                    .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AssessmentPageLayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TrackersFilledLB)
                                .addComponent(UseMWBTrafficLightLB)
                                .addComponent(UseOfSCLB)
                                .addComponent(PeerAssessmentLB)
                                .addComponent(TeacherAssessmentLB)))
                        .addComponent(SubjectSpecificDocumentLB))
                    .addComponent(TeacherAssessmentFoldersLB)
                    .addComponent(FeedbackResponseLB))
                .addGap(26, 26, 26)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YesLB3)
                    .addComponent(UseMWBTrafficLightY)
                    .addComponent(TrackersFilledY)
                    .addComponent(UseOfSCY)
                    .addComponent(PeerAssessmentY)
                    .addComponent(TeacherAssessmentY)
                    .addComponent(SubjectSpecificDocumentY)
                    .addComponent(PastPapersY)
                    .addComponent(TeacherAssessmentFoldersY)
                    .addComponent(FeedbackResponseY))
                .addGap(29, 29, 29)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UseMWBTrafficLightN)
                    .addComponent(NoLB3)
                    .addComponent(TrackersFilledN)
                    .addComponent(UseOfSCN)
                    .addComponent(PeerAssessmentN)
                    .addComponent(TeacherAssessmentN)
                    .addComponent(SubjectSpecificDocumentN)
                    .addComponent(PastPapersN)
                    .addComponent(TeacherAssessmentFoldersN)
                    .addComponent(FeedbackResponseN))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        AssessmentPageLayout.setVerticalGroup(
            AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentPageLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(AssessmentLB)
                .addGap(48, 48, 48)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssessmentPageLayout.createSequentialGroup()
                        .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YesLB3)
                            .addComponent(NoLB3))
                        .addGap(32, 32, 32)
                        .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UseMWBTrafficLightY)
                            .addComponent(UseMWBTrafficLightLB)
                            .addComponent(UseMWBTrafficLightN))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssessmentPageLayout.createSequentialGroup()
                                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TrackersFilledLB)
                                    .addComponent(TrackersFilledY)
                                    .addComponent(TrackersFilledN))
                                .addGap(18, 18, 18)
                                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UseOfSCLB)
                                    .addComponent(UseOfSCY)
                                    .addComponent(UseOfSCN))
                                .addGap(18, 18, 18)
                                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PeerAssessmentN)
                                    .addComponent(PeerAssessmentLB)
                                    .addComponent(PeerAssessmentY))
                                .addGap(18, 18, 18)
                                .addComponent(TeacherAssessmentLB))
                            .addComponent(TeacherAssessmentY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TeacherAssessmentN, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubjectSpecificDocumentLB)
                            .addComponent(SubjectSpecificDocumentN)))
                    .addGroup(AssessmentPageLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(SubjectSpecificDocumentY)))
                .addGap(18, 18, 18)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AssessmentPageLayout.createSequentialGroup()
                        .addComponent(PastPapersN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TeacherAssessmentFoldersN))
                    .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(AssessmentPageLayout.createSequentialGroup()
                            .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PastPapersLB)
                                .addComponent(PastPapersY))
                            .addGap(18, 18, 18)
                            .addComponent(TeacherAssessmentFoldersLB))
                        .addComponent(TeacherAssessmentFoldersY)))
                .addGap(18, 18, 18)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FeedbackResponseLB)
                    .addComponent(FeedbackResponseY)
                    .addComponent(FeedbackResponseN))
                .addGap(102, 102, 102)
                .addGroup(AssessmentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACommentsLB)
                    .addComponent(ACommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(ContinueButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        AScrollPane.setViewportView(AssessmentPage);

        getContentPane().add(AScrollPane, "card6");

        POESFEScrollPane.setHorizontalScrollBar(null);
        POESFEScrollPane.setPreferredSize(new java.awt.Dimension(866, 844));

        POESFEPage.setPreferredSize(new java.awt.Dimension(866, 844));

        ESSystemY.setSelected(true);

        NotesSystemLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NotesSystemLB.setText("Students are able to show/explain their system for recording notes");

        FolderNeatLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        FolderNeatLB.setText("Any folders seen are neatly kept and well organised (e.g. use of dividers)");

        ESSystemLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ESSystemLB.setText("Students are able to show/explain their system for recording Essential Study");

        POESFECommentsLB.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        POESFECommentsLB.setText("Additional Comments");

        POESFECommentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POESFECommentsFieldActionPerformed(evt);
            }
        });

        ContinueButtonPOESFE.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        ContinueButtonPOESFE.setText("Continue");
        ContinueButtonPOESFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonPOESFEActionPerformed(evt);
            }
        });

        NotesSystemY.setSelected(true);

        POESFELB.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        POESFELB.setText("Fill in the Data for");

        POESFELB2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        POESFELB2.setText(" Personal Organisation: Essential Study and Folder Etiquette");

        FolderNeatY.setSelected(true);
        FolderNeatY.setToolTipText("");

        YesLB4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        YesLB4.setText("Yes");

        NoLB4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NoLB4.setText("No");

        javax.swing.GroupLayout POESFEPageLayout = new javax.swing.GroupLayout(POESFEPage);
        POESFEPage.setLayout(POESFEPageLayout);
        POESFEPageLayout.setHorizontalGroup(
            POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POESFEPageLayout.createSequentialGroup()
                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(POESFELB2))
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(POESFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(POESFEPageLayout.createSequentialGroup()
                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(POESFECommentsLB))
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(POESFELB))
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FolderNeatLB)
                            .addComponent(NotesSystemLB)
                            .addComponent(ESSystemLB))
                        .addGap(32, 32, 32)
                        .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YesLB4)
                            .addComponent(NotesSystemY)
                            .addComponent(FolderNeatY)
                            .addComponent(ESSystemY))
                        .addGap(28, 28, 28)
                        .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ESSystemN)
                            .addComponent(NoLB4)
                            .addComponent(NotesSystemN)
                            .addComponent(FolderNeatN)))
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(ContinueButtonPOESFE, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        POESFEPageLayout.setVerticalGroup(
            POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POESFEPageLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(POESFELB)
                .addGap(18, 18, 18)
                .addComponent(POESFELB2)
                .addGap(84, 84, 84)
                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(POESFEPageLayout.createSequentialGroup()
                        .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(POESFEPageLayout.createSequentialGroup()
                                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(YesLB4)
                                    .addComponent(NoLB4))
                                .addGap(18, 18, 18)
                                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NotesSystemY)
                                    .addComponent(NotesSystemN)))
                            .addComponent(NotesSystemLB))
                        .addGap(18, 18, 18)
                        .addComponent(FolderNeatLB))
                    .addComponent(FolderNeatY)
                    .addComponent(FolderNeatN))
                .addGap(18, 18, 18)
                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ESSystemLB)
                    .addComponent(ESSystemY)
                    .addComponent(ESSystemN))
                .addGap(73, 73, 73)
                .addGroup(POESFEPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POESFECommentsLB)
                    .addComponent(POESFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(ContinueButtonPOESFE, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        POESFEScrollPane.setViewportView(POESFEPage);

        getContentPane().add(POESFEScrollPane, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButtons(){
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(StudentPostureY);
        bg1.add(StudentPostureN);
        
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(StudentSilenceY);
        bg2.add(StudentSilenceN);
        
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(StudentEngagedY);
        bg3.add(StudentEngagedN);
        
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(StudentFocusY);
        bg4.add(StudentFocusN);
        
        ButtonGroup bg5 = new ButtonGroup();
        bg5.add(StudentListeningY);
        bg5.add(StudentListeningN);
        
        ButtonGroup bg6 = new ButtonGroup();
        bg6.add(StudentRespectY);
        bg6.add(StudentRespectN);
        
        ButtonGroup bg7 = new ButtonGroup();
        bg7.add(StudentCoatHatOffY);
        bg7.add(StudentCoatHatOffN);
        
        ButtonGroup bg8 = new ButtonGroup();
        bg8.add(NoPhoneY);
        bg8.add(NoPhoneN);
        
        ButtonGroup bg9 = new ButtonGroup();
        bg9.add(NeatY);
        bg9.add(NeatN);
        
        ButtonGroup bg10 = new ButtonGroup();
        bg10.add(WOWReadingBookFilledY);
        bg10.add(WOWReadingBookFilledN);
        
        ButtonGroup bg11 = new ButtonGroup();
        bg11.add(SignedY);
        bg11.add(SignedN);
        
        ButtonGroup bg12 = new ButtonGroup();
        bg12.add(PrepDateY);
        bg12.add(PrepDateN);
        
        ButtonGroup bg13 = new ButtonGroup();
        bg13.add(NoGapsY);
        bg13.add(NoGapsN);
        
        ButtonGroup bg14 = new ButtonGroup();
        bg14.add(CoveredY);
        bg14.add(CoveredN);
        
        ButtonGroup bg15 = new ButtonGroup();
        bg15.add(HandwritingNeatY);
        bg15.add(HandwritingNeatN);
        
        ButtonGroup bg16 = new ButtonGroup();
        bg16.add(UnderlinedY);
        bg16.add(UnderlinedN);
        
        ButtonGroup bg17 = new ButtonGroup();
        bg17.add(SheetsNeatY);
        bg17.add(SheetsNeatN);
        
        ButtonGroup bg18 = new ButtonGroup();
        bg18.add(CorrectPenY);
        bg18.add(CorrectPenN);
        
        ButtonGroup bg19 = new ButtonGroup();
        bg19.add(UseMWBTrafficLightY);
        bg19.add(UseMWBTrafficLightN);
        
        ButtonGroup bg20 = new ButtonGroup();
        bg20.add(TrackersFilledY);
        bg20.add(TrackersFilledN);
        
        ButtonGroup bg21 = new ButtonGroup();
        bg21.add(UseOfSCY);
        bg21.add(UseOfSCN);
        
        ButtonGroup bg22 = new ButtonGroup();
        bg22.add(PeerAssessmentY);
        bg22.add(PeerAssessmentN);
        
        ButtonGroup bg23 = new ButtonGroup();
        bg23.add(TeacherAssessmentY);
        bg23.add(TeacherAssessmentN);
        
        ButtonGroup bg24 = new ButtonGroup();
        bg24.add(SubjectSpecificDocumentY);
        bg24.add(SubjectSpecificDocumentN);
        
        ButtonGroup bg25 = new ButtonGroup();
        bg25.add(PastPapersY);
        bg25.add(PastPapersN);
        
        ButtonGroup bg26 = new ButtonGroup();
        bg26.add(TeacherAssessmentFoldersY);
        bg26.add(TeacherAssessmentFoldersN);
        
        ButtonGroup bg27 = new ButtonGroup();
        bg27.add(FeedbackResponseY);
        bg27.add(FeedbackResponseN);
        
        ButtonGroup bg28 = new ButtonGroup();
        bg28.add(NotesSystemY);
        bg28.add(NotesSystemN);
        
        ButtonGroup bg29 = new ButtonGroup();
        bg29.add(FolderNeatY);
        bg29.add(FolderNeatN);
        
        ButtonGroup bg30 = new ButtonGroup();
        bg30.add(ESSystemY);
        bg30.add(ESSystemN);
        
    }

    
    
    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        
    }//GEN-LAST:event_DateFieldActionPerformed

    private void TeacherFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherFieldActionPerformed

    
    private void ContinueButtonCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonCDActionPerformed
        if (DateField.getText().isEmpty() && TeacherField.getText().isEmpty()) {
            DateEmptyLB.setText("Field is Empty");
            TeacherEmptyLB.setText("Field is Empty");
        } 
        else if (DateField.getText().isEmpty()) {
            DateEmptyLB.setText("Field is Empty");
        }
        else if (TeacherField.getText().isEmpty()) {
            TeacherEmptyLB.setText("Field is Empty");
        }
        else {
            
            int YrGrp = Integer.parseInt(YrGrpCombo.getSelectedItem().toString());
            int Set = Integer.parseInt(SetCombo.getSelectedItem().toString());
            String Lvl = LvlCombo.getSelectedItem().toString();
            String Sub = SubCombo.getSelectedItem().toString();
            String InputDate = DateField.getText();
            String InputDay = DayCombo.getSelectedItem().toString();
            int Period = Integer.parseInt(PeriodCombo.getSelectedItem().toString());
            String DutyTeacher = TeacherField.getText();
            String TeacherGroup = GrpCombo.getSelectedItem().toString();
            
            LBScrollPane.setVisible(true);
            Classdetailspage.setVisible(false);
        }
        
    }//GEN-LAST:event_ContinueButtonCDActionPerformed

    private void DateFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateFieldKeyReleased
        DateEmptyLB.setText("");
    }//GEN-LAST:event_DateFieldKeyReleased

    private void TeacherFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeacherFieldKeyReleased
        TeacherEmptyLB.setText("");
    }//GEN-LAST:event_TeacherFieldKeyReleased

    private void ContinueButtonLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonLBActionPerformed

        boolean StudentPosture = StudentPostureY.isSelected();
        boolean StudentSilence = StudentSilenceY.isSelected();
        boolean StudentEngaged = StudentEngagedY.isSelected();
        boolean StudentFocus = StudentFocusY.isSelected();
        boolean StudentListening = StudentListeningY.isSelected();
        boolean StudentRespect = StudentRespectY.isSelected();
        boolean StudentCoatHatOff = StudentCoatHatOffY.isSelected();
        boolean NoPhone = NoPhoneY.isSelected();
        
        POPScrollPane.setVisible(true);
        LBScrollPane.setVisible(false);

        
    }//GEN-LAST:event_ContinueButtonLBActionPerformed

    private void ContinueButtonPOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonPOPActionPerformed

        boolean Neat = NeatY.isSelected();
        boolean WOWReadingBookFilled = WOWReadingBookFilledY.isSelected();
        boolean Signed = SignedY.isSelected();
        boolean PrepDate = PrepDateY.isSelected();
        boolean NoGaps = NoGapsY.isSelected();

        POBFEScrollPane.setVisible(true);
        POPScrollPane.setVisible(false);
    }//GEN-LAST:event_ContinueButtonPOPActionPerformed

    private void POBFECommentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POBFECommentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POBFECommentsFieldActionPerformed

    private void ContinueButtonPOBFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonPOBFEActionPerformed

        boolean Covered = CoveredY.isSelected();
        boolean HandwritingNeat = HandwritingNeatY.isSelected();
        boolean Underlined = UnderlinedY.isSelected();
        boolean SheetsNeat = SheetsNeatY.isSelected();
        boolean CorrectPen = CorrectPenY.isSelected();
        String POBFEComment = POBFECommentsField.getText();
        
        AScrollPane.setVisible(true);
        POBFEScrollPane.setVisible(false);

        
    }//GEN-LAST:event_ContinueButtonPOBFEActionPerformed

    private void ContinueButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonAActionPerformed

        boolean UseMWBTrafficLight = UseMWBTrafficLightY.isSelected();
        boolean TrackersFilled = TrackersFilledY.isSelected();
        boolean UseOfSC = UseOfSCY.isSelected();
        boolean PeerAssessment = PeerAssessmentY.isSelected();
        boolean TeacherAssessment = TeacherAssessmentY.isSelected();
        boolean SubjectSpecificDocument = SubjectSpecificDocumentY.isSelected();
        boolean PastPapers = PastPapersY.isSelected();
        boolean TeacherAssessmentFolders = TeacherAssessmentFoldersY.isSelected();
        boolean FeedbackResponse = FeedbackResponseY.isSelected();
        String AComments = ACommentsField.getText();

        POESFEScrollPane.setVisible(true);
        AScrollPane.setVisible(false);
    }//GEN-LAST:event_ContinueButtonAActionPerformed

    private void POESFECommentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POESFECommentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POESFECommentsFieldActionPerformed

    private void ContinueButtonPOESFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonPOESFEActionPerformed

        
        
        
        
        
        
        new ChoicePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonPOESFEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACommentsField;
    private javax.swing.JLabel ACommentsLB;
    private javax.swing.JScrollPane AScrollPane;
    private javax.swing.JLabel AssessmentLB;
    private javax.swing.JPanel AssessmentPage;
    private javax.swing.JPanel Classdetailspage;
    private javax.swing.JButton ContinueButtonA;
    private javax.swing.JButton ContinueButtonCD;
    private javax.swing.JButton ContinueButtonLB;
    private javax.swing.JButton ContinueButtonPOBFE;
    private javax.swing.JButton ContinueButtonPOESFE;
    private javax.swing.JButton ContinueButtonPOP;
    private javax.swing.JLabel CorrectPen2LB;
    private javax.swing.JLabel CorrectPenLB;
    private javax.swing.JRadioButton CorrectPenN;
    private javax.swing.JRadioButton CorrectPenY;
    private javax.swing.JLabel CoveredLB;
    private javax.swing.JRadioButton CoveredN;
    private javax.swing.JRadioButton CoveredY;
    private javax.swing.JLabel DateEmptyLB;
    private javax.swing.JTextField DateField;
    private javax.swing.JLabel DateLB;
    private javax.swing.JComboBox<String> DayCombo;
    private javax.swing.JLabel DayLB;
    private javax.swing.JLabel ESSystemLB;
    private javax.swing.JRadioButton ESSystemN;
    private javax.swing.JRadioButton ESSystemY;
    private javax.swing.JLabel EnterDetails;
    private javax.swing.JLabel FeedbackResponseLB;
    private javax.swing.JRadioButton FeedbackResponseN;
    private javax.swing.JRadioButton FeedbackResponseY;
    private javax.swing.JLabel FolderNeatLB;
    private javax.swing.JRadioButton FolderNeatN;
    private javax.swing.JRadioButton FolderNeatY;
    private javax.swing.JComboBox<String> GrpCombo;
    private javax.swing.JLabel GrpLB;
    private javax.swing.JLabel HandwritingNeatLB;
    private javax.swing.JRadioButton HandwritingNeatN;
    private javax.swing.JRadioButton HandwritingNeatY;
    private javax.swing.JTextField LBCommentField;
    private javax.swing.JLabel LBCommentsLB;
    private javax.swing.JScrollPane LBScrollPane;
    private javax.swing.JPanel LearningBehaviourPage;
    private javax.swing.JLabel LevelLB;
    private javax.swing.JComboBox<String> LvlCombo;
    private javax.swing.JLabel NeatLB;
    private javax.swing.JRadioButton NeatN;
    private javax.swing.JRadioButton NeatY;
    private javax.swing.JLabel NoGapsLB;
    private javax.swing.JRadioButton NoGapsN;
    private javax.swing.JRadioButton NoGapsY;
    private javax.swing.JLabel NoLB;
    private javax.swing.JLabel NoLB1;
    private javax.swing.JLabel NoLB2;
    private javax.swing.JLabel NoLB3;
    private javax.swing.JLabel NoLB4;
    private javax.swing.JLabel NoPhoneLB;
    private javax.swing.JRadioButton NoPhoneN;
    private javax.swing.JRadioButton NoPhoneY;
    private javax.swing.JLabel NotesSystemLB;
    private javax.swing.JRadioButton NotesSystemN;
    private javax.swing.JRadioButton NotesSystemY;
    private javax.swing.JTextField POBFECommentsField;
    private javax.swing.JLabel POBFECommentsLB;
    private javax.swing.JPanel POBFEPage;
    private javax.swing.JScrollPane POBFEScrollPane;
    private javax.swing.JTextField POESFECommentsField;
    private javax.swing.JLabel POESFECommentsLB;
    private javax.swing.JLabel POESFELB;
    private javax.swing.JLabel POESFELB2;
    private javax.swing.JPanel POESFEPage;
    private javax.swing.JScrollPane POESFEScrollPane;
    private javax.swing.JTextField POPCommentsField;
    private javax.swing.JLabel POPCommentsLB;
    private javax.swing.JPanel POPPage;
    private javax.swing.JScrollPane POPScrollPane;
    private javax.swing.JLabel POPTitle;
    private javax.swing.JLabel PastPapersLB;
    private javax.swing.JRadioButton PastPapersN;
    private javax.swing.JRadioButton PastPapersY;
    private javax.swing.JLabel PeerAssessmentLB;
    private javax.swing.JRadioButton PeerAssessmentN;
    private javax.swing.JRadioButton PeerAssessmentY;
    private javax.swing.JComboBox<String> PeriodCombo;
    private javax.swing.JLabel PeriodLB;
    private javax.swing.JLabel PrepDateLB;
    private javax.swing.JRadioButton PrepDateN;
    private javax.swing.JRadioButton PrepDateY;
    private javax.swing.JComboBox<String> SetCombo;
    private javax.swing.JLabel SetLB;
    private javax.swing.JLabel SheetsNeatLB;
    private javax.swing.JRadioButton SheetsNeatN;
    private javax.swing.JRadioButton SheetsNeatY;
    private javax.swing.JLabel SignedLB;
    private javax.swing.JRadioButton SignedN;
    private javax.swing.JRadioButton SignedY;
    private javax.swing.JLabel StudentCoatHatOffLB;
    private javax.swing.JRadioButton StudentCoatHatOffN;
    private javax.swing.JRadioButton StudentCoatHatOffY;
    private javax.swing.JLabel StudentEngagedLB;
    private javax.swing.JRadioButton StudentEngagedN;
    private javax.swing.JRadioButton StudentEngagedY;
    private javax.swing.JLabel StudentFocusLB;
    private javax.swing.JRadioButton StudentFocusN;
    private javax.swing.JRadioButton StudentFocusY;
    private javax.swing.JLabel StudentListeningLB;
    private javax.swing.JRadioButton StudentListeningN;
    private javax.swing.JRadioButton StudentListeningY;
    private javax.swing.JLabel StudentPostureLB;
    private javax.swing.JRadioButton StudentPostureN;
    private javax.swing.JRadioButton StudentPostureY;
    private javax.swing.JLabel StudentRespectLB;
    private javax.swing.JRadioButton StudentRespectN;
    private javax.swing.JRadioButton StudentRespectY;
    private javax.swing.JLabel StudentSilenceLB;
    private javax.swing.JRadioButton StudentSilenceN;
    private javax.swing.JRadioButton StudentSilenceY;
    private javax.swing.JComboBox<String> SubCombo;
    private javax.swing.JLabel SubLB;
    private javax.swing.JLabel SubjectSpecificDocumentLB;
    private javax.swing.JRadioButton SubjectSpecificDocumentN;
    private javax.swing.JRadioButton SubjectSpecificDocumentY;
    private javax.swing.JLabel TeacherAssessmentFoldersLB;
    private javax.swing.JRadioButton TeacherAssessmentFoldersN;
    private javax.swing.JRadioButton TeacherAssessmentFoldersY;
    private javax.swing.JLabel TeacherAssessmentLB;
    private javax.swing.JRadioButton TeacherAssessmentN;
    private javax.swing.JRadioButton TeacherAssessmentY;
    private javax.swing.JLabel TeacherEmptyLB;
    private javax.swing.JTextField TeacherField;
    private javax.swing.JLabel TeacherLB;
    private javax.swing.JLabel TitleLB;
    private javax.swing.JLabel TrackersFilledLB;
    private javax.swing.JRadioButton TrackersFilledN;
    private javax.swing.JRadioButton TrackersFilledY;
    private javax.swing.JLabel UnderlinedLB;
    private javax.swing.JRadioButton UnderlinedN;
    private javax.swing.JRadioButton UnderlinedY;
    private javax.swing.JLabel UseMWBTrafficLightLB;
    private javax.swing.JRadioButton UseMWBTrafficLightN;
    private javax.swing.JRadioButton UseMWBTrafficLightY;
    private javax.swing.JLabel UseOfSCLB;
    private javax.swing.JRadioButton UseOfSCN;
    private javax.swing.JRadioButton UseOfSCY;
    private javax.swing.JLabel WOWReadingBookFilledLB;
    private javax.swing.JRadioButton WOWReadingBookFilledN;
    private javax.swing.JRadioButton WOWReadingBookFilledY;
    private javax.swing.JLabel YesLB;
    private javax.swing.JLabel YesLB1;
    private javax.swing.JLabel YesLB2;
    private javax.swing.JLabel YesLB3;
    private javax.swing.JLabel YesLB4;
    private javax.swing.JComboBox<String> YrGrpCombo;
    private javax.swing.JLabel YrGrpLB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

