/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;
/**
 *
 * @author Family
 */
public class LearningBehaviourPage extends javax.swing.JFrame {

    /**
     * Creates new form LearningBehaviourPage
     */
    public LearningBehaviourPage() {
        initComponents();
        groupButton1();
        groupButton2();
        groupButton3();
        groupButton4();
        groupButton5();
        groupButton6();
        groupButton7();
        groupButton8();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLB = new javax.swing.JLabel();
        StudentPostureLB = new javax.swing.JLabel();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        StudentSilenceLB = new javax.swing.JLabel();
        StudentEngagedLB = new javax.swing.JLabel();
        StudentFocusLB = new javax.swing.JLabel();
        StudentListeningLB = new javax.swing.JLabel();
        StudentRespectLB = new javax.swing.JLabel();
        StudentCoatHatOffLB = new javax.swing.JLabel();
        NoPhoneLB = new javax.swing.JLabel();
        LBCommentField = new javax.swing.JTextField();
        LBCommentsLB = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        StudentPostureY = new javax.swing.JRadioButton();
        StudentPostureN = new javax.swing.JRadioButton();
        StudentSilenceY = new javax.swing.JRadioButton();
        StudentSilenceN = new javax.swing.JRadioButton();
        StudentEngagedY = new javax.swing.JRadioButton();
        StudentEngagedN = new javax.swing.JRadioButton();
        StudentFocusY = new javax.swing.JRadioButton();
        StudentFocusN = new javax.swing.JRadioButton();
        StudentListeningY = new javax.swing.JRadioButton();
        StudentListeningN = new javax.swing.JRadioButton();
        StudentRespectY = new javax.swing.JRadioButton();
        StudentRespectN = new javax.swing.JRadioButton();
        StudentCoatHatOffY = new javax.swing.JRadioButton();
        StudentCoatHatOffN = new javax.swing.JRadioButton();
        NoPhoneY = new javax.swing.JRadioButton();
        NoPhoneN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(550, 100));
        setResizable(false);

        TitleLB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TitleLB.setText("Fill in the Data for Learning Behaviour");

        StudentPostureLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentPostureLB.setText("Student's Posture shows that they are alert and ready to learn");

        YesLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoLB.setText("No");

        StudentSilenceLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentSilenceLB.setText("Students remain silent unless invited to speak");

        StudentEngagedLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentEngagedLB.setText("Students appear engaged");

        StudentFocusLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentFocusLB.setText("Students remain on task during independent work");

        StudentListeningLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentListeningLB.setText("Students display good listening behaviour");

        StudentRespectLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentRespectLB.setText("Students act respectfully towards the teacher and each other");

        StudentCoatHatOffLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentCoatHatOffLB.setText("Coats and Hats have been taken off");

        NoPhoneLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoPhoneLB.setText("No phones out (unless directed by the teacher)");

        LBCommentsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBCommentsLB.setText("Additional Comments");

        ContinueButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        StudentPostureN.setSelected(true);

        StudentSilenceN.setSelected(true);

        StudentEngagedN.setSelected(true);

        StudentFocusN.setSelected(true);

        StudentListeningN.setSelected(true);

        StudentRespectN.setSelected(true);

        StudentCoatHatOffN.setSelected(true);

        NoPhoneN.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentCoatHatOffLB)
                            .addComponent(StudentRespectLB)
                            .addComponent(StudentListeningLB)
                            .addComponent(StudentFocusLB)
                            .addComponent(StudentEngagedLB)
                            .addComponent(StudentSilenceLB)
                            .addComponent(StudentPostureLB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LBCommentsLB)
                                .addComponent(NoPhoneLB)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudentPostureY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentSilenceY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentEngagedY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentFocusY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentListeningY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentRespectY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentCoatHatOffY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NoPhoneY, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(539, Short.MAX_VALUE)
                        .addComponent(YesLB)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoLB)
                    .addComponent(StudentPostureN)
                    .addComponent(StudentSilenceN)
                    .addComponent(StudentEngagedN)
                    .addComponent(StudentFocusN)
                    .addComponent(StudentListeningN)
                    .addComponent(StudentRespectN)
                    .addComponent(StudentCoatHatOffN)
                    .addComponent(NoPhoneN))
                .addGap(373, 373, 373))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBCommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(TitleLB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(TitleLB)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesLB)
                    .addComponent(NoLB))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentPostureLB)
                    .addComponent(StudentPostureY)
                    .addComponent(StudentPostureN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(StudentSilenceLB)
                        .addComponent(StudentSilenceY))
                    .addComponent(StudentSilenceN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentEngagedLB)
                    .addComponent(StudentEngagedY)
                    .addComponent(StudentEngagedN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentFocusLB)
                    .addComponent(StudentFocusY)
                    .addComponent(StudentFocusN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(StudentListeningLB)
                        .addComponent(StudentListeningY))
                    .addComponent(StudentListeningN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StudentRespectLB)
                        .addComponent(StudentRespectY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(StudentRespectN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentCoatHatOffLB)
                    .addComponent(StudentCoatHatOffY)
                    .addComponent(StudentCoatHatOffN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoPhoneLB)
                    .addComponent(NoPhoneY)
                    .addComponent(NoPhoneN))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBCommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBCommentsLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton1(){
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(StudentPostureY);
        bg1.add(StudentPostureN);
    }
    
    private void groupButton2(){
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(StudentSilenceY);
        bg2.add(StudentSilenceN);
    }
    
    private void groupButton3() {
        ButtonGroup bg3 = new ButtonGroup();
        
        bg3.add(StudentEngagedY);
        bg3.add(StudentEngagedN);
    }
    
    private void groupButton4() {
        ButtonGroup bg4 = new ButtonGroup();
        
        bg4.add(StudentFocusY);
        bg4.add(StudentFocusN);
    }
    
    private void groupButton5() {
        ButtonGroup bg5 = new ButtonGroup();
        
        bg5.add(StudentListeningY);
        bg5.add(StudentListeningN);
    }
    
    private void groupButton6() {
        ButtonGroup bg6 = new ButtonGroup();
        
        bg6.add(StudentRespectY);
        bg6.add(StudentRespectN);
    }
    
    private void groupButton7() {
        ButtonGroup bg7 = new ButtonGroup();
        
        bg7.add(StudentCoatHatOffY);
        bg7.add(StudentCoatHatOffN);
    }
    
    private void groupButton8() {
        ButtonGroup bg8 = new ButtonGroup();
        
        bg8.add(NoPhoneY);
        bg8.add(NoPhoneN);
    }
    
    
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        
        boolean StudentPosture = StudentPostureY.isSelected();
        boolean StudentSilence = StudentSilenceY.isSelected();
        boolean StudentEngaged = StudentEngagedY.isSelected();
        boolean StudentFocus = StudentFocusY.isSelected();
        boolean StudentListening = StudentListeningY.isSelected();
        boolean StudentRespect = StudentRespectY.isSelected();
        boolean StudentCoatHatOff = StudentCoatHatOffY.isSelected();
        boolean NoPhone = NoPhoneY.isSelected();
        
        DataTempStorage.LearningBehaviourStore(StudentPosture, StudentSilence, StudentEngaged, StudentFocus, StudentListening, StudentRespect, StudentCoatHatOff, NoPhone, LBCommentField.getText());
        
        new POPPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningBehaviourPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningBehaviourPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningBehaviourPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningBehaviourPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningBehaviourPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JTextField LBCommentField;
    private javax.swing.JLabel LBCommentsLB;
    private javax.swing.JLabel NoLB;
    private javax.swing.JLabel NoPhoneLB;
    private javax.swing.JRadioButton NoPhoneN;
    private javax.swing.JRadioButton NoPhoneY;
    private javax.swing.JLabel StudentCoatHatOffLB;
    private javax.swing.JRadioButton StudentCoatHatOffN;
    private javax.swing.JRadioButton StudentCoatHatOffY;
    private javax.swing.JLabel StudentEngagedLB;
    private javax.swing.JRadioButton StudentEngagedN;
    private javax.swing.JRadioButton StudentEngagedY;
    private javax.swing.JLabel StudentFocusLB;
    private javax.swing.JRadioButton StudentFocusN;
    private javax.swing.JRadioButton StudentFocusY;
    private javax.swing.JLabel StudentListeningLB;
    private javax.swing.JRadioButton StudentListeningN;
    private javax.swing.JRadioButton StudentListeningY;
    private javax.swing.JLabel StudentPostureLB;
    private javax.swing.JRadioButton StudentPostureN;
    private javax.swing.JRadioButton StudentPostureY;
    private javax.swing.JLabel StudentRespectLB;
    private javax.swing.JRadioButton StudentRespectN;
    private javax.swing.JRadioButton StudentRespectY;
    private javax.swing.JLabel StudentSilenceLB;
    private javax.swing.JRadioButton StudentSilenceN;
    private javax.swing.JRadioButton StudentSilenceY;
    private javax.swing.JLabel TitleLB;
    private javax.swing.JLabel YesLB;
    // End of variables declaration//GEN-END:variables
}
