/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;

/**
 *
 * @author Family
 */
public class POBFEPage extends javax.swing.JFrame {

    /**
     * Creates new form POBFEPage
     */
    public POBFEPage() {
        initComponents();
        
        groupButton1();
        groupButton2();
        groupButton3();
        groupButton4();
        groupButton5();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CoveredLB = new javax.swing.JLabel();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        HandwritingNeatLB = new javax.swing.JLabel();
        UnderlinedLB = new javax.swing.JLabel();
        SheetsNeatLB = new javax.swing.JLabel();
        CorrectPenLB = new javax.swing.JLabel();
        POBFECommentsLB = new javax.swing.JLabel();
        POBFECommentsField = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        CoveredY = new javax.swing.JRadioButton();
        CoveredN = new javax.swing.JRadioButton();
        HandwritingNeatY = new javax.swing.JRadioButton();
        HandwritingNeatN = new javax.swing.JRadioButton();
        UnderlinedY = new javax.swing.JRadioButton();
        UnderlinedN = new javax.swing.JRadioButton();
        SheetsNeatY = new javax.swing.JRadioButton();
        SheetsNeatN = new javax.swing.JRadioButton();
        CorrectPenY = new javax.swing.JRadioButton();
        CorrectPenN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(480, 80));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Fill in the Data for Personal Organisation: Book/Folder Etiquette");

        CoveredLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoveredLB.setText("Books are Covered");

        YesLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoLB.setText("No");

        HandwritingNeatLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HandwritingNeatLB.setText("Students make an effort to keep handwriting neat and legible");

        UnderlinedLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UnderlinedLB.setText("Students underline all dates and titles and record LOs");

        SheetsNeatLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SheetsNeatLB.setText("Sheets are stuck in neatly with no loose papers");

        CorrectPenLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CorrectPenLB.setText("Students use the correct pen (blue/black for work, red for underlining, green for assessment)");

        POBFECommentsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        POBFECommentsLB.setText("Additional Comments");

        POBFECommentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POBFECommentsFieldActionPerformed(evt);
            }
        });

        ContinueButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        CoveredN.setSelected(true);

        HandwritingNeatN.setSelected(true);

        UnderlinedN.setSelected(true);

        SheetsNeatN.setSelected(true);

        CorrectPenN.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesLB)
                                .addGap(52, 52, 52)
                                .addComponent(NoLB))
                            .addComponent(CoveredN)
                            .addComponent(HandwritingNeatN)
                            .addComponent(UnderlinedN)
                            .addComponent(SheetsNeatN)
                            .addComponent(CorrectPenN))
                        .addGap(514, 514, 514))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UnderlinedLB)
                                    .addComponent(HandwritingNeatLB)
                                    .addComponent(SheetsNeatLB)
                                    .addComponent(CorrectPenLB)
                                    .addComponent(POBFECommentsLB)
                                    .addComponent(CoveredLB))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(POBFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CoveredY)
                                    .addComponent(HandwritingNeatY)
                                    .addComponent(UnderlinedY)
                                    .addComponent(SheetsNeatY)
                                    .addComponent(CorrectPenY)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel1)))
                        .addContainerGap(94, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesLB)
                    .addComponent(NoLB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(CoveredLB))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CoveredY)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CoveredN)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HandwritingNeatLB)
                        .addComponent(HandwritingNeatY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(HandwritingNeatN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UnderlinedLB)
                    .addComponent(UnderlinedY)
                    .addComponent(UnderlinedN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SheetsNeatLB)
                        .addComponent(SheetsNeatY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(SheetsNeatN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorrectPenLB)
                    .addComponent(CorrectPenY)
                    .addComponent(CorrectPenN))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POBFECommentsLB)
                    .addComponent(POBFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton1() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(CoveredY);
        bg1.add(CoveredN);
    }
    
    private void groupButton2() {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(HandwritingNeatY);
        bg2.add(HandwritingNeatN);
    }
    
    private void groupButton3() {
        ButtonGroup bg3 = new ButtonGroup();
        
        bg3.add(UnderlinedY);
        bg3.add(UnderlinedN);
    }
    
    private void groupButton4() {
        ButtonGroup bg4 = new ButtonGroup();
        
        bg4.add(SheetsNeatY);
        bg4.add(SheetsNeatN);
    }
    
    private void groupButton5() {
        ButtonGroup bg5 = new ButtonGroup();
        
        bg5.add(CorrectPenY);
        bg5.add(CorrectPenN);
    }
    
    
    private void POBFECommentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POBFECommentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POBFECommentsFieldActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        
        boolean Covered = CoveredY.isSelected();
        boolean HandwritingNeat = HandwritingNeatY.isSelected();
        boolean Underlined = UnderlinedY.isSelected();
        boolean SheetsNeat = SheetsNeatY.isSelected();
        boolean CorrectPen = CorrectPenY.isSelected();
        String POBFEComment = POBFECommentsField.getText();
        
        DataTempStorage.POBFEStore(Covered, HandwritingNeat, Underlined, SheetsNeat, CorrectPen, POBFEComment);
        
        new AssessmentPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POBFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POBFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POBFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POBFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POBFEPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel CorrectPenLB;
    private javax.swing.JRadioButton CorrectPenN;
    private javax.swing.JRadioButton CorrectPenY;
    private javax.swing.JLabel CoveredLB;
    private javax.swing.JRadioButton CoveredN;
    private javax.swing.JRadioButton CoveredY;
    private javax.swing.JLabel HandwritingNeatLB;
    private javax.swing.JRadioButton HandwritingNeatN;
    private javax.swing.JRadioButton HandwritingNeatY;
    private javax.swing.JLabel NoLB;
    private javax.swing.JTextField POBFECommentsField;
    private javax.swing.JLabel POBFECommentsLB;
    private javax.swing.JLabel SheetsNeatLB;
    private javax.swing.JRadioButton SheetsNeatN;
    private javax.swing.JRadioButton SheetsNeatY;
    private javax.swing.JLabel UnderlinedLB;
    private javax.swing.JRadioButton UnderlinedN;
    private javax.swing.JRadioButton UnderlinedY;
    private javax.swing.JLabel YesLB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
