/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;

/**
 *
 * @author Family
 */
public class POESFEPage extends javax.swing.JFrame {

    /**
     * Creates new form POESFEPage
     */
    public POESFEPage() {
        initComponents();
        
        groupButton1();
        groupButton2();
        groupButton3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POESFELB = new javax.swing.JLabel();
        POESFELB2 = new javax.swing.JLabel();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        NotesSystemLB = new javax.swing.JLabel();
        FolderNeatLB = new javax.swing.JLabel();
        ESSystemLB = new javax.swing.JLabel();
        POESFECommentsLB = new javax.swing.JLabel();
        POESFECommentsField = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        NotesSystemY = new javax.swing.JRadioButton();
        NotesSystemN = new javax.swing.JRadioButton();
        FolderNeatY = new javax.swing.JRadioButton();
        FolderNeatN = new javax.swing.JRadioButton();
        ESSystemY = new javax.swing.JRadioButton();
        ESSystemN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(480, 80));
        setResizable(false);

        POESFELB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        POESFELB.setText("Fill in the Data for Personal Organisation: Essential Study");

        POESFELB2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        POESFELB2.setText("and Folder Etiquette");

        YesLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoLB.setText("No");

        NotesSystemLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NotesSystemLB.setText("Students are able to show/explain their system for recording notes");

        FolderNeatLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FolderNeatLB.setText("Any folders seen are neatly kept and well organised (e.g. use of dividers)");

        ESSystemLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ESSystemLB.setText("Students are able to show/explain their system for recording Essential Study");

        POESFECommentsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        POESFECommentsLB.setText("Additional Comments");

        POESFECommentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POESFECommentsFieldActionPerformed(evt);
            }
        });

        ContinueButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        NotesSystemN.setSelected(true);

        FolderNeatY.setToolTipText("");

        FolderNeatN.setSelected(true);

        ESSystemN.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(POESFELB2)
                        .addGap(621, 621, 621))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FolderNeatLB)
                                .addComponent(NotesSystemLB)
                                .addComponent(ESSystemLB)
                                .addComponent(POESFECommentsLB))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(POESFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(YesLB)
                                        .addComponent(NotesSystemY)
                                        .addComponent(FolderNeatY)
                                        .addComponent(ESSystemY))
                                    .addGap(61, 61, 61)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ESSystemN)
                                        .addComponent(NoLB)
                                        .addComponent(NotesSystemN)
                                        .addComponent(FolderNeatN))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(POESFELB)
                            .addGap(344, 344, 344)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(POESFELB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(POESFELB2)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(YesLB)
                                    .addComponent(NoLB))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NotesSystemY)
                                    .addComponent(NotesSystemN)))
                            .addComponent(NotesSystemLB))
                        .addGap(18, 18, 18)
                        .addComponent(FolderNeatLB))
                    .addComponent(FolderNeatY)
                    .addComponent(FolderNeatN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ESSystemLB)
                    .addComponent(ESSystemY)
                    .addComponent(ESSystemN))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POESFECommentsLB)
                    .addComponent(POESFECommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton1() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(NotesSystemY);
        bg1.add(NotesSystemN);
    }
    
    private void groupButton2() {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(FolderNeatY);
        bg2.add(FolderNeatN);
    }
    
    private void groupButton3() {
        ButtonGroup bg3 = new ButtonGroup();
        
        bg3.add(ESSystemY);
        bg3.add(ESSystemN);
    }
    
    
    private void POESFECommentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POESFECommentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POESFECommentsFieldActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        
        
        
        
        
        
        
        
        new ChoicePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POESFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POESFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POESFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POESFEPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POESFEPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel ESSystemLB;
    private javax.swing.JRadioButton ESSystemN;
    private javax.swing.JRadioButton ESSystemY;
    private javax.swing.JLabel FolderNeatLB;
    private javax.swing.JRadioButton FolderNeatN;
    private javax.swing.JRadioButton FolderNeatY;
    private javax.swing.JLabel NoLB;
    private javax.swing.JLabel NotesSystemLB;
    private javax.swing.JRadioButton NotesSystemN;
    private javax.swing.JRadioButton NotesSystemY;
    private javax.swing.JTextField POESFECommentsField;
    private javax.swing.JLabel POESFECommentsLB;
    private javax.swing.JLabel POESFELB;
    private javax.swing.JLabel POESFELB2;
    private javax.swing.JLabel YesLB;
    // End of variables declaration//GEN-END:variables
}
