/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nea;

import javax.swing.ButtonGroup;

/**
 *
 * @author Family
 */
public class POPPage extends javax.swing.JFrame {

    /**
     * Creates new form POPPage
     */
    public POPPage() {
        initComponents();
        
        groupButton1();
        groupButton2();
        groupButton3();
        groupButton4();
        groupButton5();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POPTitle = new javax.swing.JLabel();
        NeatLB = new javax.swing.JLabel();
        YesLB = new javax.swing.JLabel();
        NoLB = new javax.swing.JLabel();
        WOWReadingBookFilledLB = new javax.swing.JLabel();
        SignedLB = new javax.swing.JLabel();
        PrepDateLB = new javax.swing.JLabel();
        NoGapsLB = new javax.swing.JLabel();
        POPCommentsLB = new javax.swing.JLabel();
        POPCommentsField = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        NeatY = new javax.swing.JRadioButton();
        NeatN = new javax.swing.JRadioButton();
        WOWReadingBookFilledY = new javax.swing.JRadioButton();
        WOWReadingBookFilledN = new javax.swing.JRadioButton();
        SignedY = new javax.swing.JRadioButton();
        SignedN = new javax.swing.JRadioButton();
        PrepDateY = new javax.swing.JRadioButton();
        PrepDateN = new javax.swing.JRadioButton();
        NoGapsY = new javax.swing.JRadioButton();
        NoGapsN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("William Perkin Monitoring System");
        setLocation(new java.awt.Point(550, 90));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        POPTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        POPTitle.setText("Fill in the Data for Personal Organisation: Planners");

        NeatLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NeatLB.setText("Planners are kept neat with no scribbles/doodles etc.");

        YesLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YesLB.setText("Yes");

        NoLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoLB.setText("No");

        WOWReadingBookFilledLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WOWReadingBookFilledLB.setText("WOW/Literacy Focus and Current Reading Book filled in");

        SignedLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignedLB.setText("Planners are signed weekly by parent and tutor");

        PrepDateLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrepDateLB.setText("Prep/HWKs are recorded clearly with due date");

        NoGapsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoGapsLB.setText("No gaps are left - if 'No Prep', a reason is recorded");

        POPCommentsLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        POPCommentsLB.setText("Additional Comments");

        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        NeatN.setSelected(true);

        WOWReadingBookFilledN.setSelected(true);

        SignedN.setSelected(true);

        PrepDateN.setSelected(true);

        NoGapsN.setSelected(true);
        NoGapsN.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(POPTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WOWReadingBookFilledLB)
                            .addComponent(NeatLB)
                            .addComponent(SignedLB)
                            .addComponent(PrepDateLB)
                            .addComponent(NoGapsLB))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PrepDateY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PrepDateN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NeatY)
                                .addGap(78, 78, 78)
                                .addComponent(NeatN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(WOWReadingBookFilledY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WOWReadingBookFilledN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SignedY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SignedN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NoGapsY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NoGapsN))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(POPCommentsLB)
                        .addGap(145, 145, 145)
                        .addComponent(POPCommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(YesLB)
                .addGap(72, 72, 72)
                .addComponent(NoLB)
                .addGap(473, 473, 473))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(POPTitle)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesLB)
                    .addComponent(NoLB))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NeatLB)
                    .addComponent(NeatY)
                    .addComponent(NeatN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(WOWReadingBookFilledLB)
                        .addComponent(WOWReadingBookFilledY, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(WOWReadingBookFilledN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SignedLB)
                    .addComponent(SignedN)
                    .addComponent(SignedY, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrepDateLB)
                    .addComponent(PrepDateY)
                    .addComponent(PrepDateN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NoGapsLB)
                        .addComponent(NoGapsY, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(NoGapsN))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POPCommentsLB)
                    .addComponent(POPCommentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton1() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(NeatY);
        bg1.add(NeatN);
    }
    
    private void groupButton2() {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(WOWReadingBookFilledY);
        bg2.add(WOWReadingBookFilledN);
    }
    
    private void groupButton3() {
        ButtonGroup bg3 = new ButtonGroup();
        
        bg3.add(SignedY);
        bg3.add(SignedN);
    }
    
    private void groupButton4() {
        ButtonGroup bg4 = new ButtonGroup();
        
        bg4.add(PrepDateY);
        bg4.add(PrepDateN);
    }
    
    private void groupButton5() {
        ButtonGroup bg5 = new ButtonGroup();
        
        bg5.add(NoGapsY);
        bg5.add(NoGapsN);
    }
    
    
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        
        boolean Neat = NeatY.isSelected();
        boolean WOWReadingBookFilled = WOWReadingBookFilledY.isSelected();
        boolean Signed = SignedY.isSelected();
        boolean PrepDate = PrepDateY.isSelected();
        boolean NoGaps = NoGapsY.isSelected();
        
        DataTempStorage.POPStore(Neat, WOWReadingBookFilled, Signed, PrepDate, NoGaps, POPCommentsField.getText());
        
        
        
        new POBFEPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POPPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel NeatLB;
    private javax.swing.JRadioButton NeatN;
    private javax.swing.JRadioButton NeatY;
    private javax.swing.JLabel NoGapsLB;
    private javax.swing.JRadioButton NoGapsN;
    private javax.swing.JRadioButton NoGapsY;
    private javax.swing.JLabel NoLB;
    private javax.swing.JTextField POPCommentsField;
    private javax.swing.JLabel POPCommentsLB;
    private javax.swing.JLabel POPTitle;
    private javax.swing.JLabel PrepDateLB;
    private javax.swing.JRadioButton PrepDateN;
    private javax.swing.JRadioButton PrepDateY;
    private javax.swing.JLabel SignedLB;
    private javax.swing.JRadioButton SignedN;
    private javax.swing.JRadioButton SignedY;
    private javax.swing.JLabel WOWReadingBookFilledLB;
    private javax.swing.JRadioButton WOWReadingBookFilledN;
    private javax.swing.JRadioButton WOWReadingBookFilledY;
    private javax.swing.JLabel YesLB;
    // End of variables declaration//GEN-END:variables
}
